[tool.poetry]
name = "aw-server"
version = "0.8"
description = ""
authors = ["Erik Bjäreholt <erik@bjareho.lt>"]
license = "MPL-2.0"

[tool.poetry.scripts]
aw-server = "aw_server:main"

[tool.poetry.dependencies]
python = "^3.6"
aw-core = {git = "https://github.com/ActivityWatch/aw-core.git"}
aw-client = {git = "https://github.com/ActivityWatch/aw-client.git"}
flask-restplus = "^0.13.0"
appdirs = "^1.4.3"
flask = "^1.1.1"
flask-cors = "^3.0.8"

[tool.poetry.dev-dependencies]
pyinstaller = "^3.5"
mypy = "^0.761"
pytest = "^5.3.2"
pytest-flask = "^0.15.0"
pytest-benchmark = "^3.2.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
